name: Build and Release

on:
  push:
    branches:
      - testbuild

jobs:
  build-and-package:
    runs-on: ubuntu-latest
    container:
      image: rafradek/ubuntu2004dev:latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Checkout AMBuild
      uses: actions/checkout@v4
      with:
        repository: alliedmodders/ambuild
        path: alliedmodders/ambuild

    - name: Checkout Sourcemod
      uses: actions/checkout@v4
      with:
        repository: alliedmodders/sourcemod
        path: alliedmodders/sourcemod

    - name: Clone and install AMBuild
      run: |
        pwd
        ls -l
        cd ..
        pwd
        ls -l
        cd alliedmodders/ambuild
        python -m pip install .
        echo 'export PATH=~/.local/bin:$PATH' >> ~/.bashrc
        source ~/.bashrc

    - name: Print Python packages and PATH
      run: |
        echo "Python packages:"
        pip list
        echo "PATH: $PATH"
        echo "Python location: $(which python)"
        echo "Python version: $(python --version)"
        python -m site

    - name: Clone sourcemod and hl2sdk
      run: |
        pushd ..
        mkdir -p alliedmodders
        cd alliedmodders
        git clone --recursive https://github.com/alliedmodders/sourcemod --depth 1 -b 1.11-dev
        git clone https://github.com/alliedmodders/hl2sdk --depth 1 -b sdk2013 hl2sdk-sdk2013
        git clone https://github.com/TF2-DMB/hl2sdk-tf2.git --depth 1 hl2sdk-tf2
        git clone https://github.com/alliedmodders/hl2sdk --depth 1 -b css hl2sdk-css
        git clone https://github.com/alliedmodders/metamod-source --depth 1 -b 1.11-dev
        popd

    - name: Build submodules
      run: |
        echo "export PATH=$HOME/.local/bin:$PATH" >> $GITHUB_ENV
        pushd libs/udis86
        ./autogen.sh
        ./configure
        make
        popd

    - name: Build Lua
      run: |
        pushd libs
        wget https://www.lua.org/ftp/lua-5.4.4.tar.gz
        tar -xf lua-*.tar.gz
        rm lua-*.tar.gz
        mv lua-* lua
        cd lua
        make MYCFLAGS='-m32' MYLDFLAGS='-m32'
        popd

    - name: Configure and build with AMBuild
      run: |
        echo "export PATH=$HOME/.local/bin:$PATH" >> $GITHUB_ENV
        export PATH=$HOME/.local/bin:$PATH
        PATH=$HOME/.local/bin:$PATH
        pip list
        echo $PATH
        ./autoconfig.sh

        ./multibuild.sh
        echo "Project built."

    - name: Upload package-linux
      uses: actions/upload-artifact@v4
      with:
        name: package-linux
        path: build/release/package-linux.zip

    - name: Upload package-linux-optimize-only
      uses: actions/upload-artifact@v4
      with:
        name: package-linux-optimize-only
        path: build/release/package-linux-optimize-only.zip

    - name: Upload package-linux-no-mvm
      uses: actions/upload-artifact@v4
      with:
        name: package-linux-no-mvm
        path: build/release/package-linux-no-mvm.zip